FROM nvidia/cuda:11.1-cudnn8-devel

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
	python3-opencv ca-certificates python3-dev git wget sudo ninja-build
RUN ln -sv /usr/bin/python3 /usr/bin/python

RUN apt-get update && apt-get install -y curl apt-utils sudo unzip\
    openssh-server passwd libgl1-mesa-glx gcc git python3-opencv ca-certificates python3-dev wget nano ninja-build


# create a non-root user
ARG USER_ID=1000
RUN useradd -m --no-log-init --system  --uid ${USER_ID} exp -g sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER exp
WORKDIR /home/exp

ENV PATH="/home/exp/.local/bin:${PATH}"
RUN wget https://bootstrap.pypa.io/get-pip.py && \
	python3 get-pip.py --user && \
	rm get-pip.py

RUN pip install --user tensorboard cmake   # cmake from apt-get is too old
RUN pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

RUN pip install --user 'git+https://github.com/facebookresearch/fvcore'

RUN git clone https://github.com/qiank10/detectron2.git 
RUN cd detectron2 && git checkout alt-0.1.1

# ENV FORCE_CUDA="1"

# RUN cd detectron2 && pip install -e .
# RUN pip install --user -e detectron2
ENV FVCORE_CACHE="/tmp"

COPY ./requirements.txt /home/exp/

RUN pip install --upgrade pip

RUN pip install -r /home/exp/requirements.txt

RUN curl https://rclone.org/install.sh | sudo bash

RUN mkdir /home/exp/data && \
    mkdir /home/exp/code && \
	mkdir /home/exp/temp

ENTRYPOINT sudo service ssh restart && bash

